In [14]:
# import library
import pandas as pd
import pickle 
from tensorflow.keras.models import load_model
import numpy as np

In [2]:
# import data imference 
data_inf = pd.read_csv('imference.csv')

In [3]:
data_inf.head()

,user_id,age,gender,region_category,membership_category,joining_date,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,...,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,8ae6522d3133d3b9,32,F,Town,Premium Membership,2015-06-16,Yes,Gift Vouchers/Coupons,Smartphone,Fiber_Optic,...,999.906388,35708.76,26.0,704.790000,Yes,No,No,Not Applicable,Poor Product Quality,0
1,b102d17d4a844600,32,M,City,Gold Membership,2016-12-04,NaN,Credit/Debit Card Offers,NaN,Wi-Fi,...,0.000000,66238.64,4.0,725.530000,Yes,No,No,Not Applicable,User Friendly Website,0
2,8b25accd593a8805,23,F,NaN,Basic Membership,2015-11-09,Yes,Credit/Debit Card Offers,Smartphone,Wi-Fi,...,72.130000,43077.99,21.0,933.854443,No,Yes,No,Not Applicable,Poor Product Quality,1
3,8413b64fc9a1cccf,41,M,Town,Gold Membership,2017-04-08,Yes,Credit/Debit Card Offers,Desktop,Fiber_Optic,...,132.260000,20795.97,17.0,654.480000,Yes,No,Yes,No Information Available,Poor Product Quality,1
4,af2963739a1d20cf,32,M,NaN,Premium Membership,2015-03-17,No,Without Offers,Desktop,Mobile_Data,...,55.780000,26361.71,4.0,736.320000,No,Yes,No,Not Applicable,Products always in Stock,0

In [4]:
# pemisahan target aktual
aktual = data_inf['churn_risk_score']

In [5]:
# Import preproses
preproses = pickle.load(open('preproses.pkl', 'rb'))

In [7]:
# Transform ke data inference
data_inf_final = preproses.transform(data_inf)

In [10]:
# import model 
model = load_model('model.h5')

In [16]:
# predik data inference
resul_predict = model.predict(data_inf_final)
resul_predict = np.where(resul_predict >= 0.5, 1, 0)
resul_predict

2/2 [==============================] - 0s 2ms/step

array([[0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1]])

In [18]:
# menyimpan hasil predik ke data frame
resul_predict = pd.DataFrame(resul_predict, columns=['Prediction'])

In [19]:
# menggabungkan hasil 
compare = pd.concat([aktual,resul_predict], axis=1)
compare.columns = ['Actual', 'Prediction']
compare

    Actual  Prediction
0        0           0
1        0           0
2        1           1
3        1           1
4        0           0
5        1           1
6        1           1
7        1           1
8        0           0
9        1           1
10       0           1
11       0           0
12       0           0
13       1           1
14       0           0
15       1           1
16       1           1
17       1           1
18       0           0
19       0           0
20       0           0
21       1           1
22       1           1
23       0           0
24       0           0
25       1           1
26       1           1
27       1           1
28       0           0
29       1           1
30       1           1
31       1           1
32       0           1
33       1           1
34       0           0
35       1           1
36       0           0
37       0           0
38       0           0
39       1           1
40       0           0
41       1           1
42       0           0
43       0           0
44       0           0
45       0           0
46       1           1
47       0           0
48       0           0
49       1           1